{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "cveId": "CVE-2025-3730",
        "assignerOrgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
        "state": "PUBLISHED",
        "assignerShortName": "VulDB",
        "dateReserved": "2025-04-16T13:41:20.997Z",
        "datePublished": "2025-04-16T21:00:17.836Z",
        "dateUpdated": "2025-05-22T21:39:19.138Z"
    },
    "containers": {
        "cna": {
            "providerMetadata": {
                "orgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
                "shortName": "VulDB",
                "dateUpdated": "2025-05-22T21:39:19.138Z"
            },
            "title": "PyTorch LossCTC.cpp torch.nn.functional.ctc_loss denial of service",
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "type": "CWE",
                            "cweId": "CWE-404",
                            "lang": "en",
                            "description": "Denial of Service"
                        }
                    ]
                }
            ],
            "affected": [
                {
                    "vendor": "n/a",
                    "product": "PyTorch",
                    "versions": [
                        {
                            "version": "2.6.0",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A vulnerability, which was classified as problematic, was found in PyTorch 2.6.0. Affected is the function torch.nn.functional.ctc_loss of the file aten/src/ATen/native/LossCTC.cpp. The manipulation leads to denial of service. An attack has to be approached locally. The exploit has been disclosed to the public and may be used. The real existence of this vulnerability is still doubted at the moment. The name of the patch is 46fc5d8e360127361211cb237d5f9eef0223e567. It is recommended to apply a patch to fix this issue. The security policy of the project warns to use unknown models which might establish malicious effects."
                },
                {
                    "lang": "de",
                    "value": "Es wurde eine Schwachstelle in PyTorch 2.6.0 gefunden. Sie wurde als problematisch eingestuft. Hiervon betroffen ist die Funktion torch.nn.functional.ctc_loss der Datei aten/src/ATen/native/LossCTC.cpp. Mit der Manipulation mit unbekannten Daten kann eine denial of service-Schwachstelle ausgenutzt werden. Der Angriff hat dabei lokal zu erfolgen. Der Exploit steht zur öffentlichen Verfügung. Die wahre Existenz der vermeintlichen Schwachstelle wird zur Zeit in Frage gestellt. Der Patch wird als 46fc5d8e360127361211cb237d5f9eef0223e567 bezeichnet. Als bestmögliche Massnahme wird Patching empfohlen."
                }
            ],
            "metrics": [
                {
                    "cvssV4_0": {
                        "version": "4.0",
                        "baseScore": 4.8,
                        "vectorString": "CVSS:4.0/AV:L/AC:L/AT:N/PR:L/UI:N/VC:N/VI:N/VA:L/SC:N/SI:N/SA:N",
                        "baseSeverity": "MEDIUM"
                    }
                },
                {
                    "cvssV3_1": {
                        "version": "3.1",
                        "baseScore": 3.3,
                        "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
                        "baseSeverity": "LOW"
                    }
                },
                {
                    "cvssV3_0": {
                        "version": "3.0",
                        "baseScore": 3.3,
                        "vectorString": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
                        "baseSeverity": "LOW"
                    }
                },
                {
                    "cvssV2_0": {
                        "version": "2.0",
                        "baseScore": 1.7,
                        "vectorString": "AV:L/AC:L/Au:S/C:N/I:N/A:P"
                    }
                }
            ],
            "timeline": [
                {
                    "time": "2025-04-16T00:00:00.000Z",
                    "lang": "en",
                    "value": "Advisory disclosed"
                },
                {
                    "time": "2025-04-16T02:00:00.000Z",
                    "lang": "en",
                    "value": "VulDB entry created"
                },
                {
                    "time": "2025-05-22T23:44:11.000Z",
                    "lang": "en",
                    "value": "VulDB entry last update"
                }
            ],
            "credits": [
                {
                    "lang": "en",
                    "value": "Default436352 (VulDB User)",
                    "type": "reporter"
                }
            ],
            "references": [
                {
                    "url": "https://vuldb.com/?id.305076",
                    "name": "VDB-305076 | PyTorch LossCTC.cpp torch.nn.functional.ctc_loss denial of service",
                    "tags": [
                        "vdb-entry",
                        "technical-description"
                    ]
                },
                {
                    "url": "https://vuldb.com/?ctiid.305076",
                    "name": "VDB-305076 | CTI Indicators (IOB, IOC, IOA)",
                    "tags": [
                        "signature",
                        "permissions-required"
                    ]
                },
                {
                    "url": "https://vuldb.com/?submit.553645",
                    "name": "Submit #553645 | pytorch pytorch (in torch.nn.functional.ctc_loss) 2.6.0 Denial of Service",
                    "tags": [
                        "third-party-advisory"
                    ]
                },
                {
                    "url": "https://github.com/pytorch/pytorch/issues/150835",
                    "tags": [
                        "issue-tracking"
                    ]
                },
                {
                    "url": "https://github.com/pytorch/pytorch/pull/150981",
                    "tags": [
                        "issue-tracking"
                    ]
                },
                {
                    "url": "https://github.com/pytorch/pytorch/issues/150835#issue-2979082232",
                    "tags": [
                        "exploit",
                        "issue-tracking"
                    ]
                },
                {
                    "url": "https://github.com/timocafe/tewart-pytorch/commit/46fc5d8e360127361211cb237d5f9eef0223e567",
                    "tags": [
                        "patch"
                    ]
                }
            ],
            "tags": [
                "disputed"
            ]
        },
        "adp": [
            {
                "references": [
                    {
                        "url": "https://github.com/pytorch/pytorch/issues/150835",
                        "tags": [
                            "exploit"
                        ]
                    }
                ],
                "metrics": [
                    {
                        "other": {
                            "type": "ssvc",
                            "content": {
                                "timestamp": "2025-04-17T13:30:13.460308Z",
                                "id": "CVE-2025-3730",
                                "options": [
                                    {
                                        "Exploitation": "poc"
                                    },
                                    {
                                        "Automatable": "no"
                                    },
                                    {
                                        "Technical Impact": "partial"
                                    }
                                ],
                                "role": "CISA Coordinator",
                                "version": "2.0.3"
                            }
                        }
                    }
                ],
                "title": "CISA ADP Vulnrichment",
                "providerMetadata": {
                    "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
                    "shortName": "CISA-ADP",
                    "dateUpdated": "2025-04-17T13:56:07.001Z"
                }
            }
        ]
    }
}